//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingLogService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEntry
    {
        public int ID { get; set; }
        public int TypeID { get; set; }
        public double Time { get; set; }
        public System.DateTime Date { get; set; }
    }
}
