//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingLogService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TrainingLogEntities : DbContext
    {
        public TrainingLogEntities()
            : base("name=TrainingLogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LogEntry> LogEntries { get; set; }
        public virtual DbSet<ExerciseType> ExerciseTypes { get; set; }
    
        public virtual ObjectResult<GetAllTrainingLogs_Result> GetAllTrainingLogs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllTrainingLogs_Result>("GetAllTrainingLogs");
        }
    }
}
